variable "aws_access_key" {}
variable "aws_secret_key" {}
variable "wp_db_name" {}
variable "wp_db_user" {}
variable "wp_db_pass" {}
variable "wp_admin_name" {}
variable "wp_admin_pass" {}
variable "wp_admin_email" {}
variable "aws_key_pair" {}
